spring:
  application:
    name: tk
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://152.136.207.239:3306/gopher?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: gopher@lee@2020.com
server:
  port: 7999
